# Generated by Django 3.2.9 on 2021-12-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ppleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Surname', models.CharField(max_length=200)),
                ('Firstname', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Phone', models.IntegerField()),
                ('date_of_birth', models.CharField(max_length=200)),
                ('BVN', models.IntegerField()),
                ('address', models.CharField(max_length=150)),
                ('guarantor_name', models.CharField(max_length=100)),
                ('state_of_origin', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('school_degree', models.CharField(max_length=300)),
            ],
        ),
    ]
